USE Project3160;

-- /*
DROP TABLE `rating`;

CREATE TABLE `rating` (
  `rating_id` mediumint(8) unsigned NOT NULL auto_increment,
  `rater_id` mediumint unsigned NOT NULL,
  `rating_num` mediumint default NULL,
  `comment` TEXT default NULL,
  PRIMARY KEY (`rating_id`),
  FOREIGN KEY (rater_id) REFERENCES person(person_id)
) AUTO_INCREMENT=1;

INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (40,1,"ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque"),(17,4,"natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."),(12,5,"diam. Sed diam lorem, auctor quis, tristique"),(37,1,"eu metus. In lorem. Donec elementum, lorem"),(76,2,"Cras convallis convallis dolor."),(83,1,"et magnis dis parturient montes,"),(65,4,"in sodales elit erat"),(19,2,"Cras eu tellus eu"),(67,1,"dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus."),(76,5,"elit, pretium et, rutrum non,");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (24,4,"at fringilla"),(79,5,"ut, molestie"),(43,4,"lectus pede et risus. Quisque libero lacus, varius"),(49,1,"vitae aliquam eros turpis non enim. Mauris quis"),(47,1,"consequat auctor,"),(88,1,"aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod"),(31,2,"amet, dapibus id, blandit at, nisi. Cum"),(46,5,"egestas nunc sed libero. Proin sed"),(48,2,"dolor. Donec fringilla. Donec feugiat metus sit amet ante."),(7,2,"justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (24,1,"in aliquet lobortis, nisi"),(21,3,"et risus. Quisque libero lacus, varius"),(43,1,"tristique pharetra. Quisque ac libero nec ligula"),(2,2,"adipiscing lobortis risus. In mi pede, nonummy ut,"),(63,2,"odio. Etiam ligula tortor, dictum"),(38,5,"id risus quis diam luctus"),(19,3,"ipsum primis in faucibus orci luctus et"),(100,1,"lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim"),(40,3,"Nam consequat dolor vitae dolor. Donec"),(51,2,"mauris ut mi. Duis risus odio, auctor vitae, aliquet");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (1,4,"tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante"),(22,3,"convallis convallis dolor. Quisque"),(34,3,"arcu. Aliquam ultrices iaculis odio. Nam interdum enim non"),(66,3,"non, egestas a, dui."),(12,2,"iaculis, lacus pede sagittis augue, eu"),(26,3,"ut mi. Duis risus odio, auctor vitae, aliquet"),(42,3,"non, egestas a, dui."),(28,4,"faucibus lectus, a sollicitudin orci sem eget massa."),(7,4,"Quisque varius. Nam porttitor scelerisque"),(33,4,"odio sagittis semper. Nam");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (12,1,"et magnis dis parturient"),(73,5,"tempor arcu."),(7,2,"ipsum porta elit, a feugiat tellus"),(61,5,"ultrices, mauris ipsum porta elit,"),(31,2,"Donec elementum, lorem"),(13,2,"nunc risus varius orci, in consequat enim diam vel"),(23,4,"non leo. Vivamus nibh dolor, nonummy"),(51,2,"Donec est. Nunc ullamcorper, velit"),(64,3,"Mauris magna."),(52,1,"montes, nascetur ridiculus mus. Proin vel arcu eu");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (83,4,"laoreet, libero et"),(37,1,"non"),(25,3,"sit amet ornare lectus"),(71,4,"quis, pede. Suspendisse"),(76,2,"ligula"),(94,2,"Morbi sit amet"),(14,5,"erat, eget tincidunt"),(7,2,"iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus."),(39,5,"sollicitudin commodo ipsum. Suspendisse non leo. Vivamus"),(55,1,"ac, eleifend vitae, erat.");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (50,3,"vel pede blandit"),(33,1,"a purus. Duis elementum, dui quis accumsan convallis, ante lectus"),(63,3,"In"),(32,3,"vel lectus. Cum sociis natoque penatibus"),(39,3,"egestas rhoncus."),(50,5,"Etiam ligula"),(73,2,"ipsum primis in faucibus orci luctus"),(99,4,"dapibus"),(51,3,"Phasellus in felis."),(7,4,"malesuada vel, venenatis vel, faucibus id,");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (95,4,"pharetra ut,"),(21,4,"quis accumsan convallis, ante lectus convallis est, vitae sodales nisi"),(30,1,"turpis vitae purus gravida sagittis. Duis gravida. Praesent eu"),(33,5,"erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat"),(2,2,"nec, malesuada ut,"),(39,1,"dapibus"),(92,3,"cursus non, egestas"),(86,5,"nisl arcu iaculis enim, sit amet"),(8,1,"tristique senectus et netus et malesuada fames ac"),(66,1,"sit amet lorem semper auctor. Mauris vel turpis.");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (11,3,"egestas hendrerit neque. In ornare"),(51,2,"Ut tincidunt vehicula risus. Nulla eget"),(25,2,"at auctor ullamcorper, nisl"),(30,5,"ridiculus mus."),(73,4,"eu metus. In lorem. Donec elementum, lorem ut"),(61,4,"mus. Proin vel nisl."),(78,2,"a, arcu. Sed et libero. Proin mi. Aliquam"),(19,5,"ante dictum"),(52,4,"at, velit. Cras lorem lorem, luctus ut,"),(82,5,"neque. Sed eget lacus. Mauris non dui nec urna suscipit");
INSERT INTO `rating` (`rater_id`,`rating_num`,`comment`) VALUES (55,2,"metus sit amet ante. Vivamus non lorem"),(98,5,"Lorem ipsum dolor sit amet, consectetuer adipiscing"),(13,4,"ut mi. Duis risus odio, auctor vitae, aliquet nec,"),(80,4,"congue a, aliquet vel, vulputate"),(45,2,"mauris. Morbi non sapien molestie orci tincidunt adipiscing."),(10,1,"natoque penatibus et magnis dis parturient montes,"),(37,4,"lorem, luctus"),(7,5,"Duis ac"),(63,2,"Maecenas malesuada fringilla est."),(95,3,"Mauris blandit enim consequat purus. Maecenas libero est, congue");
